#' Photovoltaic energy production
#' 
#' This function determines the power generated by a photovoltaic system
#' @param area is the solar panel area (m2),
#' @param r is panel yield (0-1) (manufacture efficiency - usually around 0.2),
#' @param PR is performance ratio (0-1) (accounting for site factors that impact efficiency usually around 0.75),
#' @param H is annual average solar radiation (kWh),
#' @return energy (kWh)
#'
# function definition
solar_poweR = function(area, r = 0.2, PR = 0.75, H) {
  result = area * r * PR * H
  return(result)
}

