---
title: "Calibration Workshop"
author: "Sarah Lam"
date: "2023-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
```

# In Class Exercise

* Read in the *sager.txt* data

* Think of a new metric that might be interesting from a particular environmental context

* Code that metric as a function - and then apply it

# Using multiple metrics. 

* depends on what you want the model to get right

* type of data that you have for evaluation (its resolution and accuracy)


```{r}
sager <- read.table(here("data", "sager.txt"), header=T)
sager = sager %>% mutate(date = paste(day,month,year, sep="/"))
sager$date = as.Date(sager$date,"%d/%m/%Y")

monthly_means <- sager %>% 
  group_by(wy, month) %>% 
  summarize(mean_obs = mean(obs), mean_model = mean(model))

mean_monthly_error <- monthly_means %>% 
  mutate(diff = mean_model-mean_obs) %>% 
  ungroup() %>% 
  summarize(mean(diff))

mean_monthly_error <- function(obs, model, wy, month){
  flow_data <- cbind.data.frame(obs, model, wy, month)
  
  mean_error <- flow_data %>% 
  group_by(wy, month) %>% 
  summarize(mean_obs = mean(obs), mean_model = mean(model)) %>% 
  mutate(diff = mean_model-mean_obs) %>% 
  ungroup() %>% 
  summarize(mean(diff))
  
  return(mean_error$"mean(diff)")
}

mean_monthly_error(obs=sager$obs, model=sager$model, wy=sager$wy, month=sager$month)
```

```{r}
#correlation coefficient
cor_coeff <- cor(monthly_means$mean_model, monthly_means$mean_obs)

obs_mean_monthly_error <- abs(mean_monthly_error)

combined = .5*obs_mean_monthly_error + .5*cor_coeff
```

```{r}
msage = read.table(here("data", "sagerm.txt"), header=T)

# keep track of number of simulations (e.g results for each parameter set) 
# use as a column names
nsim = ncol(msage)
snames = sprintf("S%d",seq(from=1, to=nsim))
colnames(msage)=snames


# lets say we know the start date from our earlier output
msage$date = sager$date
msage$month = sager$month
msage$year = sager$year
msage$day = sager$day
msage$wy = sager$wy

# lets add observed
msage = left_join(msage, sager[,c("obs","date")], by=c("date"))
```

```{r}
# subset for split sample calibration
short_msage = subset(msage, wy < 1975)

# compute performance measures for output from all parameters
res <- short_msage %>% select(!c("date","month","year","day","wy","obs")) %>%
      map_dbl(mean_monthly_error, short_msage$obs, short_msage$wy, short_msage$month) # purrr function here! map_dbl will apply the function to each column in our data frame against the observed and returns a vector

```



